version: "3"

services:
  database:
    image: mariadb
    environment:
      - MYSQL_DATABASE=collabtrack
      - MYSQL_USER=collabtrack
      - MYSQL_PASSWORD=wUWTYqGbIJSgAJFWAwKQ
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    volumes:
      - /home/kevin/development/collabtrack/mysql_volume:/var/lib/mysql
      
  application:
    image: kevinpinhoiamin/collabtrack-application
    volumes:
      - /home/kevin/development/collabtrack/uploads:/collabtrack/_uploads
    depends_on:
      - database

  nginx:
    image: kevinpinhoiamin/collabtrack-nginx
    ports:
      - 80:80
    depends_on:
      - application

  nginx-test:
    image: nginx
    ports:
      - 81:80
    depends_on:
      - application
    volumes:
      - /home/kevin/development/collabtrack/test:/usr/share/nginx/html

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: database
    depends_on:
      - database